Repository bonggongii/bonggongiiBot, pull requests merged in 2024-11, with the labels that each got.

#14 [feat] gpt 응답 streaming 적용
  app/src/main/java/com/project/bonggong/ChatContract.kt
  app/src/main/java/com/project/bonggong/model/GptApiRequest.kt
  app/src/main/java/com/project/bonggong/model/Message.kt
  app/src/main/java/com/project/bonggong/presenter/ChatPresenter.kt
  app/src/main/java/com/project/bonggong/view/ChatActivity.kt
Labels: ✨ feat, 🎀 refactor, 🔧 hotfix

#15 [Feat] 채팅창 header 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/bonggong/SplashActivity.kt
  app/src/main/java/com/project/bonggong/view/ChatActivity.kt
  app/src/main/res/drawable/header_background.xml
  app/src/main/res/drawable/ic_menu.png
  app/src/main/res/drawable/ic_refresh.png
  app/src/main/res/drawable/main_bonggong.png
  app/src/main/res/drawable/main_description.png
  app/src/main/res/drawable/main_text.png
  app/src/main/res/drawable/splash_test.png
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  sss
Labels: ✨ feat, ❤️ style

#16 [feat] 채팅창 화면에 헤더, 챗봇 가이드 추가 및 초기화 버튼 구현
  app/src/main/java/com/project/bonggong/view/ChatActivity.kt
  app/src/main/res/drawable/header_background.xml
  app/src/main/res/drawable/ic_menu.png
  app/src/main/res/drawable/ic_refresh.png
  app/src/main/res/drawable/main_bonggong.png
  app/src/main/res/drawable/main_description.png
  app/src/main/res/drawable/main_text.png
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat, ❤️ style

#21 [fix] 채팅 초기화 시, 액티비티 재실행하는 것으로 변경
  app/src/main/java/com/project/bonggong/view/ChatActivity.kt
Labels: 🔧 fix

#28 [feat] copyright, 약관 및 정책 추가
  app/src/main/java/com/project/bonggong/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat, ❤️ style
